# artifact project settings

# Note: {cwd} == current directory of THIS file
#       {repo} == directory of the `.art` file

# directories containing artifact toml files
artifact_paths = ["{repo}/design"]

# artifact paths to exclude. This is how you can avoid trying
# to load .git/.hg/etc directories (or anything else you don't
# want to include
exclude_artifact_paths = ["{repo}/.git", "{repo}/resource", "{repo}/target"]

# directories containing code that has artifact links
code_paths = ["{repo}/src", "{repo}/tests"]

# directories to exclude when searching through code
exclude_code_paths = [] # ["{repo}/target", "{repo}/resource", "{repo}/.git"]
